<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">HiTraining</a>
    &raquo; <a class="" href="<?php echo $this->url('hi-training/exercise-type');?>">Exercise type</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-training/exercise-type/stats');?>">Exercise type stats</a>
</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'Exercise type stats';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div style="float:left; width: 340px;">
        <?php echo $tree;?>
    </div>
    <div style="float: right; width: 740px;">
        <?php
        $this->headStyle()->appendStyle(
            '
            .ui-tabs .ui-tabs-hide {
                position: absolute;
                left: -10000px;
                display: block !important;
            }
            '
        );
        ?>
        <div id="tabs">
            <ul>
                <li><a href="#tabs-1">Time</a></li>
                <li><a href="#tabs-2">Avg Speed</a></li>
                <li><a href="#tabs-3">Fat loss</a></li>
                <li><a href="#tabs-4">Fat loss/min</a></li>
                <li><a href="#tabs-5">HR</a></li>
<!--                <li><a href="#tabs-5">Bones</a></li>-->
                <li><a href="#tabs-6">Calories</a></li>
                <li><a href="#tabs-7">Calories/min</a></li>
<!--                <li><a href="#tabs-7">BMI</a></li>-->
<!--                <li><a href="#tabs-8">Circumferences</a></li>-->
            </ul>
            <div id="tabs-1" style="width: 900px;">
                <div id="time_div" style="width: 700px; height: 200px;"></div>
            </div>
            <div id="tabs-2" >
                <div id="avg_speed_div" style="width: 700px; height: 200px;"></div>
<!--                <div id="FatPercent_div" style="width: 700px; height: 200px;"></div>-->
            </div>
            <div id="tabs-3" style="width: 900px;">
                <div id="fat_loss_div" style="width: 700px; height: 200px;"></div>
            </div>
            <div id="tabs-4" style="width: 900px;">
                <div id="fat_lossmin_div" style="width: 700px; height: 200px;"></div>
            </div>
            <div id="tabs-5" style="width: 900px;">
                <div id="HRavg_div" style="width: 700px; height: 200px;"></div>
                <div id="HRmax_div" style="width: 700px; height: 200px;"></div>
            </div>
<!--            <div id="tabs-5" style="width: 900px;">-->
<!--                <div id="BonesW_div" style="width: 700px; height: 200px;"></div>-->
<!--                <div id="BonesPercent_div" style="width: 700px; height: 200px;"></div>-->
<!--            </div>-->
            <div id="tabs-6" style="width: 900px;">
                <div id="Calories_div" style="width: 700px; height: 200px;"></div>
            </div>
            <div id="tabs-7" style="width: 900px;">
                <div id="Caloriesmin_div" style="width: 700px; height: 200px;"></div>
            </div>
<!--            <div id="tabs-7" style="width: 900px;">-->
<!--                <div id="BMI_div" style="width: 700px; height: 200px;"></div>-->
<!--            </div>-->
<!--            <div id="tabs-8" style="width: 900px;">-->
<!--                <div id="WaistC_div" style="width: 700px; height: 200px;"></div>-->
<!--                <div id="ChestC_div" style="width: 700px; height: 200px;"></div>-->
<!--                <div id="NeckC_div" style="width: 700px; height: 200px;"></div>-->
<!--                <div id="BicepsC_div" style="width: 700px; height: 200px;"></div>-->
<!--            </div>-->
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<?php
//@TODO change from array to object
$exercisesArray = array();
if ($exercises) {
    $exercisesArray = $exercises->toArray();
}
\Zend\Debug::dump($exercisesArray);
?>

<?php $this->headScript()->appendFile('https://www.google.com/jsapi', 'text/javascript');?>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawCharts);
    function drawCharts() {
        $( "#tabs" ).tabs();

        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Time');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php
              $timeArray = explode(':', $exercise['exercise_elapsed_time']);
              $time = sprintf('%.2f', ($timeArray[0] * 3600 + $timeArray[1] * 60 + $timeArray[2] * 1) / 60);
          ?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo $time;?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('time_div'));
        chart.draw(data, options);


        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Avg Speed');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php if ($exercise['avg_speed'] <= 0) continue;?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo $exercise['avg_speed'];?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('avg_speed_div'));
        chart.draw(data, options);


        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Fat loss');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php if ($exercise['fat_loss'] <= 0) continue;?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo $exercise['fat_loss'];?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('fat_loss_div'));
        chart.draw(data, options);


        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'HR max');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php if ($exercise['hr_max'] <= 0) continue;?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo $exercise['hr_max'];?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('HRmax_div'));
        chart.draw(data, options);


        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'HR avg');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php if ($exercise['hr_avg'] <= 0) continue;?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo $exercise['hr_avg'];?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('HRavg_div'));
        chart.draw(data, options);


        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Calories');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php if ($exercise['exercise_calories_burned'] <= 0) continue;?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo $exercise['exercise_calories_burned'];?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('Calories_div'));
        chart.draw(data, options);
        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Fat loss mg/min');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php
              if ($exercise['fat_loss'] <= 0) continue;

              $timeArray = explode(':', $exercise['exercise_elapsed_time']);
              $time = ($timeArray[0] * 3600 + $timeArray[1] * 60 + $timeArray[2] * 1) / 60;
          ?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo ($exercise['fat_loss']/$time) * 1000;;?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('fat_lossmin_div'));
        chart.draw(data, options);


        //--------------------------------------------------
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Calories/min');

        data.addRows([
          <?php foreach ($exercisesArray as $exercise):?>
          <?php
                  if ($exercise['exercise_calories_burned'] <= 0) continue;

                  $timeArray = explode(':', $exercise['exercise_elapsed_time']);
                  $time = ($timeArray[0] * 3600 + $timeArray[1] * 60 + $timeArray[2] * 1) / 60;
              ?>
          ['<?php echo $exercise['workout_date'];?>', <?php echo ($exercise['exercise_calories_burned']/$time) ;?>],
          <?php endforeach;?>
        ]);

        var options = {
          //title: 'Weight'
        };

        var chart = new google.visualization.LineChart(document.getElementById('Caloriesmin_div'));
        chart.draw(data, options);
<?php /*?>

    /**
	*
	* /
    var dataFatW = new google.visualization.DataTable();
    dataFatW.addColumn('string', 'Date');
    dataFatW.addColumn('number', 'Fat Weight [kg]');
    dataFatW.addColumn({type:'number', role:'interval'});  // interval role col.
    dataFatW.addColumn({type:'number', role:'interval'});  // interval role col.
    dataFatW.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['fat_weight'];?>, <?php echo $exercise['fat_weight_range_bottom'];?>, <?php echo $exercise['fat_weight_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Fat Weight'
//    };

    var chartFatW = new google.visualization.LineChart(document.getElementById('FatW_div'));
    chartFatW.draw(dataFatW, options);

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Fat Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['fat_percentage'];?>, <?php echo $exercise['fat_percentage'] - 0.1 ;?>, <?php echo $exercise['fat_percentage'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartFatPercent = new google.visualization.LineChart(document.getElementById('FatPercent_div'));
    chartFatPercent.draw(data, options);

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Muscle Weight [kg]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.

    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['muscle_weight'];?>, <?php echo $exercise['muscle_weight_range_bottom'];?>, <?php echo $exercise['muscle_weight_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Weight'
//    };

    var chartMuscleW = new google.visualization.LineChart(document.getElementById('MuscleW_div'));
    chartMuscleW.draw(data, options);

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Muscle Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['muscle_percentage'];?>, <?php echo $exercise['muscle_percentage'] - 0.1 ;?>, <?php echo $exercise['muscle_percentage'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartMusclePercent = new google.visualization.LineChart(document.getElementById('MusclePercent_div'));
    chartMusclePercent.draw(data, options);







    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Water Weight [kg]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['water_weight'];?>, <?php echo $exercise['water_weight_range_bottom'];?>, <?php echo $exercise['water_weight_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Weight'
//    };

    var chartWaterW = new google.visualization.LineChart(document.getElementById('WaterW_div'));
    chartWaterW.draw(data, options);

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Water Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['water_percentage'];?>, <?php echo $exercise['water_percentage'] - 0.1 ;?>, <?php echo $exercise['water_percentage'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartWaterPercent = new google.visualization.LineChart(document.getElementById('WaterPercent_div'));
    chartWaterPercent.draw(data, options);



    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Bones Weight [kg]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['bones_weight'];?>, <?php echo $exercise['bones_weight'] - 0.1 ;?>, <?php echo $exercise['bones_weight'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Weight'
//    };

    var chartBonesW = new google.visualization.LineChart(document.getElementById('BonesW_div'));
    chartBonesW.draw(data, options);

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Bones Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['bones_percentage'];?>, <?php echo $exercise['bones_percentage_range_bottom'];?>, <?php echo $exercise['bones_percentage_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartBonesPercent = new google.visualization.LineChart(document.getElementById('BonesPercent_div'));
    chartBonesPercent.draw(data, options);


    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Calories A4 [kcal]');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['calories_active'];?>],
      <?php endforeach;?>
    ]);

    var chartCaloriesA4 = new google.visualization.LineChart(document.getElementById('CaloriesA4_div'));
    chartCaloriesA4.draw(data, options);
//

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Calories [kcal]');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['calories_activeless'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartCalories = new google.visualization.LineChart(document.getElementById('Calories_div'));
    chartCalories.draw(data, options);

    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'BMI');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['bmi'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartCalories = new google.visualization.LineChart(document.getElementById('BMI_div'));
    chartCalories.draw(data, options);


    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Waist Circumference');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['waist_circumference'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartCalories = new google.visualization.LineChart(document.getElementById('WaistC_div'));
    chartCalories.draw(data, options);
    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Neck Circumference');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['neck_circumference'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartCalories = new google.visualization.LineChart(document.getElementById('NeckC_div'));
    chartCalories.draw(data, options);
    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Chest Circumference');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['chest_circumference'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartCalories = new google.visualization.LineChart(document.getElementById('ChestC_div'));
    chartCalories.draw(data, options);
    /**
	*
	* /
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Biceps Circumference');
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
//    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($exercisesArray as $exercise):?>
      ['<?php echo $exercise['date'];?>', <?php echo $exercise['biceps_circumference'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartCalories = new google.visualization.LineChart(document.getElementById('BicepsC_div'));
    chartCalories.draw(data, options);

*/ ?>
  }
</script>



