<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">HiTraining</a>
    &raquo; <a class="" href="<?php echo $this->url('hi-training/exercise-type');?>">Exercise type</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-training/exercise-type/tree');?>">Exercise type tree</a>
</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'Exercise type tree';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div style="float:left; width: 340px;">
        <?php echo $tree;?>
    </div>
    <div style="float: right; width: 740px;">
        <?php //echo $type;?>
        <table>
            <tr>
                <td>type_img</td>
                <td>
                <?php if (is_array($type['type_img']) && count($type['type_img'])) foreach ($type['type_img'] as $img) :?>
                    <img alt="guide_img" src="<?php echo $img; ?>" />
                <?php endforeach;?>


                </td>
            </tr>
            <tr>
                <td>guide_img</td>
                <td>
                    <img alt="guide_img" src="<?php echo $type['guide_img']?>" />
                    <img alt="guide_img" src="" /><?php echo $this->ShowImage($type['guide_img'])?>
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td><?php echo $type['name']?></td>
            </tr>
            <tr>
                <td>Description</td>
                <td><?php echo $type['description']?></td>
            </tr>
            <tr>
                <td>Link</td>
                <td><a href="<?php echo $type['link']?>" ><?php echo $type['link']?></a></td>
            </tr>
            <tr>
                <td>mechanics_type</td>
                <td><?php echo $type['mechanics_type']?></td>
            </tr>
            <tr>
                <td>rating</td>
                <td><?php echo $type['rating']?></td>
            </tr>
            <tr>
                <td>force_type</td>
                <td><?php echo $type['force_type']?></td>
            </tr>

        </table>
        <?php //\Zend\Debug::dump($type->toArray());;?>
    </div>
    <div style="clear: both;"></div>


</div>


