<div id="breadcrumb">
    &raquo;<a href="<?php echo $this->url('home');?>">Core/index/index</a>
    &raquo;<a class="" href="<?php echo $this->url('exercises-home');?>">Exercises/index/index</a>
    &raquo;<a class="" href="<?php echo $this->url('exercises-checkup-home');?>">Exercises/checkup/index</a>
    &raquo;Exercises/checkup/delete
</div>
<div id="menu">
    <div class="modules">
        <a class="selected" href="<?php echo $this->url('exercises-home');?>" >Exercises</a>
    </div>
    <div class="module-elements">
        <a class="selected" href="<?php echo $this->url('exercises-checkup-home');?>" >Checkups</a>
        <a href="<?php echo $this->url('exercises-workout-home');?>" >Workouts</a>
        <a href="<?php //echo $this->url('exercises-workout-type');?>" >Workout Types</a>
        <a href="<?php //echo $this->url('exercises-workout-group');?>" >Workout Groups</a>
    </div>
</div>
<div id="content">

    <?php
        $title = 'Delete checkup';
        $this->headTitle($title);
    ?>
    <h1><?php echo $this->escape($title); ?></h1>

    <p>Are you sure that you want to delete
    '<?php echo $this->escape($checkup['date']); ?>' checkup?
    </p>

    <?php  $url = $this->url('exercises-checkup-delete') . '?checkup_id=' . $checkup->checkup_id; ?>
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="checkup_id" value="<?php echo (int)$checkup->checkup_id; ?>" />
            <input type="submit" name="del" value="Yes" />
            <input type="submit" name="del" value="No" />
        </div>
    </form>
</div>