<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-checkup');?>">HiCheckup</a>
    &raquo; <a href="<?php echo $this->url('hi-checkup/checkup-profile/list');?>">Checkup profile list</a>
    &raquo; <a class="selected" href="">Add checkup profile</a>

</div>

<div id="content">
	<div class="page-title">
        <?php
            $title = 'Add new checkup profile';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>

    <?php echo $form;?>
</div>