<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-checkup');?>">HiCheckup</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-checkup/checkup-profile');?>">Checkup profile</a>
</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'Checkup profile';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    Bla Bla
</div>

