<div id="breadcrumb">
	&raquo;<a class="" href="<?php echo $this->url('home');?>">Core/index/index</a>
    &raquo;Core/error/dispatch
</div>
<div id="menu">
<a href="<?php echo $this->url('exercises-home');?>">Exercises</a>
</div>
<div id="content">

    <div class="code_500">
    <h2>Application Error</h2>

    <p>
        An error occurred processing this page; please try again later.
    </p>

    <?php
    if (!$this->display_exceptions) {
        echo "<p>Display exceptions is disabled</p>\n";
        return;
    }
    $exception = $this->exception;
    if (!$exception instanceof \Exception) {
        echo "<p>Invalid exception found</p>\n";
        return;
    }
    ?>
    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?php echo $this->vars()->escape($exception->getMessage()) ?>
    </p>

    <h3>Stack trace:</h3>
    <pre>
    <?php echo $exception->getTraceAsString() ?>
    </pre>

    </div>
</div>

