<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">HiTraining</a>

</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'HiTraining';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    BlaBla
</div>
