<tr class="listActions" >
    <td>
        <?php if (is_array($this->langs)):?>
            <?php foreach ($this->langs as $lang):?>
                <a
                    href="?form=<?php echo $this->subFormId;?>&lang=<?php echo $lang;?>"
                    ><?php if ($lang == $this->lang) :?><b><?php endif;?>[<?php echo mb_strtoupper($lang, 'utf-8');?>]<?php if ($lang == $this->lang) :?></b><?php endif;?></a>
            <?php endforeach;?>
        <?php endif;?>
    </td>
    <td
        <?php if (isset($this->colspan)):?>
        colspan="<?php echo $this->colspan ?>"
        <?php endif;?>
        class=""
        align="right"
        >
        <?php echo $this->content;?>
    </td>
</tr>