<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
    <head>
        <?php echo $this->headTitle();?>
        <?php echo $this->headMeta(); ?>

        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>

        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <?php echo $this->layout()->content;?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
<!-- END OF PAGE -->
