<div class="container">
    <table class="" width="100%" cellspacing="0" cellpadding="2" border="0">
        <tr>
            <td  width="25%" valign="top">
                <?php echo $this->tree;?>
            </td>
            <td valign="top">
                <?php echo $this->edit;?>
            </td>
        </tr>
        <tr>
            <td>
                <div class="error">
                    <?php echo $this->error;?>
                </div>
            </td>
        </tr>
    </table>
</div>



