<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">Training</a>
    &raquo; <a class="" href="<?php echo $this->url('hi-training/checkup/list');?>">Checkup list</a>
    &raquo; <a class="selected" href="">Add Checkup</a>

</div>

<div id="content">
	<div class="page-title">
        <?php
            $title = 'Add new checkup';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>

    <?php echo $form;?>
</div>