<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">HiTraining</a>
    &raquo; <a href="<?php echo $this->url('hi-training/workout');?>">Workout</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-training/workout/list');?>">Workout list</a>

</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'Workout list';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>

    <?php echo $form;?>
</div>
