<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">HiTraining</a>
    &raquo; <a class="" href="<?php echo $this->url('hi-training/workout');?>">Workout</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-training/workout/stats');?>">Workout statisctics</a>
</div>

<div id="content">
    <div class="page-title">
        <?php
            $title = 'Workout statistics';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div>


    <?php
    //@TODO change from array to object
    $workoutsArray = array();
    if ($workouts) {
        $workoutsArray = $workouts->toArray();
    }

//    \Zend\Debug::dump($workoutsArray);
    ?>

    <br />
<?php $this->headScript()->appendFile('https://www.google.com/jsapi', 'text/javascript');?>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawCharts);
    function drawCharts() {
        $( "#tabs" ).tabs();




    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Time');

    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
      <?php
          $timeArray = explode(':', $workout['elapsed_time']);
          $time = ($timeArray[0] * 3600 + $timeArray[1] * 60 + $timeArray[2] * 1) / 60;
      ?>
      <?php if ($time <= 0) continue;?>
      ['<?php echo $workout['date'];?>', <?php echo $time;?>],
      <?php endforeach;?>
    ]);

    var options = {
      //title: 'Weight'
    };

    var chart = new google.visualization.LineChart(document.getElementById('time_div'));
    chart.draw(data, options);


    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Calories');
    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
      <?php if ($workout['calories_burned'] <= 0) continue;?>
      ['<?php echo $workout['date'];?>', <?php echo $workout['calories_burned'];?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('kcal_div'));
    chart.draw(data, options);


    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'HRmax');
    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
      <?php if ($workout['hr_max'] <= 0) continue;?>
      ['<?php echo $workout['date'];?>', <?php echo $workout['hr_max'];?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('HRmax_div'));
    chart.draw(data, options);

    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'HRavg');
    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
      <?php if ($workout['hr_avg'] <= 0) continue;?>
      ['<?php echo $workout['date'];?>', <?php echo $workout['hr_avg'];?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('HRavg_div'));
    chart.draw(data, options);


    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Fat loss');
    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
      <?php if ($workout['fat_loss'] <= 0) continue;?>
      ['<?php echo $workout['date'];?>', <?php echo $workout['fat_loss'];?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('fat_div'));
    chart.draw(data, options);



    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Calories/min');
    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
          <?php if ($workout['calories_burned'] <= 0) continue;?>
          <?php
              $timeArray = explode(':', $workout['elapsed_time']);
              $time = ($timeArray[0] * 3600 + $timeArray[1] * 60 + $timeArray[2] * 1) / 60;
          ?>
      ['<?php echo $workout['date'];?>', <?php echo $workout['calories_burned']/$time;?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('calsec_div'));
    chart.draw(data, options);

    //--------------------------------------
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'mg Fat/min');
    data.addRows([
      <?php foreach ($workoutsArray as $workout):?>
          <?php if ($workout['fat_loss'] <= 0) continue;?>
          <?php
              $timeArray = explode(':', $workout['elapsed_time']);
              $time = ($timeArray[0] * 3600 + $timeArray[1] * 60 + $timeArray[2] * 1) / 60;
          ?>
      ['<?php echo $workout['date'];?>', <?php echo ($workout['fat_loss']/$time) * 1000;?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('mgfatsec_div'));
    chart.draw(data, options);


    //--------------------------------------
    /*
    <?php
        $work = array();
        foreach ($workoutsArray as $workout){
            $year = date('Y', strtotime($workout['date']));
            $week = date('W', strtotime($workout['date']));
            if (!empty($work[$year][$week])) {
                $work[$year][$week] += 1;
            } else {
                $work[$year][$week] = 1;
            }
        }

        //\Zend\Debug::dump($work);

    ?>
    */
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Week stats');
    data.addRows([
      <?php foreach ($work as $year => $weeks):?>
          <?php foreach ($weeks as $week => $count):?>

               ['<?php echo $year . '-' . $week;?>', <?php echo $count;?>],
          <?php endforeach;?>
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('week_div'));
    chart.draw(data, options);


    //--------------------------------------
    /*
    <?php
        $work = array();
        foreach ($workoutsArray as $workout){
            $year = date('Y', strtotime($workout['date']));
            $month = date('m', strtotime($workout['date']));
            if (!empty($work[$year][$month])) {
                $work[$year][$month] += 1;
            } else {
                $work[$year][$month] = 1;
            }
        }

        //\Zend\Debug::dump($work);

    ?>
    */
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Month stats');
    data.addRows([
      <?php foreach ($work as $year => $months):?>
          <?php foreach ($months as $month => $count):?>

               ['<?php echo $year . '-' . $month;?>', <?php echo $count;?>],
          <?php endforeach;?>
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.LineChart(document.getElementById('month_div'));
    chart.draw(data, options);


    //--------------------------------------
    /*
    <?php
        //
        $work = array();

        //
        $first = array_shift($workoutsArray);array_unshift($workoutsArray, $first);
        $last = array_pop($workoutsArray); array_push($workoutsArray, $last);

        //
        $firstTimestamp = strtotime($first['date']);
        $lastTimestamp = strtotime($last['date']);

        while(date('Y-m-d', $firstTimestamp) != date('Y-m-d', $lastTimestamp)) {

            $work[date('Y-m-d', $firstTimestamp)] = 0;

            $firstTimestamp = mktime(
                0,
                0,
                0,
                date("m", $firstTimestamp),
                date("d", $firstTimestamp)+1,
                date("Y", $firstTimestamp)
            );

        }
//        \Zend\Debug::dump($work);

        foreach ($workoutsArray as $workout){

            $year = date('Y', strtotime($workout['date']));
            $month = date('m', strtotime($workout['date']));
            $day = date('d', strtotime($workout['date']));
            if (!empty($work[$year . '-' . $month . '-' . $day])) {
                $work[$year . '-' . $month . '-' . $day] += 1;
            } else {
                $work[$year . '-' . $month . '-' . $day] = 1;
            }
        }

//        \Zend\Debug::dump($work);

    ?>
    */
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Calendar');
    data.addRows([
      <?php foreach ($work as $date => $count):?>
          ['<?php echo $date;?>', <?php echo $count;?>],
      <?php endforeach;?>
    ]);

    var chart = new google.visualization.ColumnChart(document.getElementById('calendar_div'));
    chart.draw(data, options);

  }
</script>

	<?php
    $this->headStyle()->appendStyle(
        '
        .ui-tabs .ui-tabs-hide {
            position: absolute;
            left: -10000px;
            display: block !important;
        }
        '
    );
    ?>

    <div id="tabs">
        <ul>
            <li><a href="#tabs-5">Calendar</a></li>
            <li><a href="#tabs-1">Time</a></li>
            <li><a href="#tabs-2">HR</a></li>
            <li><a href="#tabs-3">Calories</a></li>
            <li><a href="#tabs-4">Fat loss</a></li>

        </ul>
        <div id="tabs-5" style="width: 900px;">
            <div id="calendar_div" style="width: 800px; height: 200px;"></div>
            <div id="week_div" style="width: 800px; height: 200px;"></div>
            <div id="month_div" style="width: 800px; height: 200px;"></div>
        </div>
        <div id="tabs-1" style="width: 900px;">
            <div id="time_div" style="width: 800px; height: 200px;"></div>
        </div>
        <div id="tabs-2" style="width: 900px;">
            <div id="HRmax_div" style="width: 800px; height: 200px;"></div>
            <div id="HRavg_div" style="width: 800px; height: 200px;"></div>
        </div>
        <div id="tabs-3" >
            <div id="kcal_div" style="width: 800px; height: 200px;"></div>
            <div id="calsec_div" style="width: 800px; height: 200px;"></div>
        </div>
        <div id="tabs-4" style="width: 900px;">
            <div id="fat_div" style="width: 800px; height: 200px;"></div>
            <div id="mgfatsec_div" style="width: 800px; height: 200px;"></div>
        </div>

    </div>
</div>

