<strong>Module:</strong>        Exercises &raquo;
<strong>Controller:</strong>    workout &raquo;
<strong>Action:</strong>        delete

<?php
$title = 'Delete workout';
$this->headTitle($title);
?>
<h1><?php echo $this->escape($title); ?></h1>
<p>Are you sure that you want to delete
'<?php echo $this->escape($workout['date']); ?>' workout?
</p>
<?php
$url = $this->url('exercises-workout-delete'); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int)$workout['id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>