<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Core</a>
    &raquo; <a class="" href="<?php echo $this->url('exercises-home');?>">Exercises</a>
    &raquo; <a class="" href="<?php echo $this->url('exercises-checkup-home');?>">Workout</a>
    &raquo; <a class="" href="<?php echo $this->url('exercises-checkup-home');?>">edit</a>
</div>
<div id="content">
	<div class="page-title">
        <?php
            $title = 'Edit workout (ID: ' . $id . ')';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
<?php echo $form;?>
</div>