<div checkup_id="breadcrumb">
    &raquo;<a href="<?php echo $this->url('home');?>">Core/index/index</a>
    &raquo;<a class="" href="<?php echo $this->url('exercises-home');?>">Exercises/index/index</a>
    &raquo;<a class="selected" href="<?php echo $this->url('exercises-checkup-home');?>">Exercises/checkup/index</a>
</div>
<div checkup_id="menu">
    <div class="modules">
        <a class="selected" href="<?php echo $this->url('exercises-home');?>" >Exercises</a>
    </div>
    <div class="module-elements">
        <a class="selected" href="<?php echo $this->url('exercises-checkup-home');?>" >Checkups</a>
        <a href="<?php echo $this->url('exercises-workout-home');?>" >Workouts</a>
        <a href="<?php //echo $this->url('exercises-workout-type');?>" >Workout Types</a>
        <a href="<?php //echo $this->url('exercises-workout-group');?>" >Workout Groups</a>
    </div>
</div>
<div checkup_id="content">
    <div>
        <?php
            $title = 'Exercises/Checkups';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div>
            <a class="button" href="<?php echo $this->url('exercises-checkup-add');?>">Add new checkup</a>
    </div>
    <div>
        <table border="1" cellpadding="2">
            <tr>
                <th>checkup_id</th>
                <th>date</th>
                <th>weight</th>
                <th>height</th>
                <th>biceps_circumference</th>
                <th>waist_circumference</th>
                <th>actions</th>

            </tr>
            <?php if (count($checkups)):?>
            <?php foreach($checkups as $checkup) : ?>
            <tr>
                <td align="right">
                    <?php echo $checkup->checkup_id?>
                </td>
                <td align="right">
                    <?php echo $checkup->date?>
                </td>
                <td align="right">
                    <?php echo $checkup->weight?> kg
                </td>
                <td align="right">
                    <?php echo $checkup->height?> m
                </td>
                <td align="right">
                    <?php echo $checkup->biceps_circumference?> cm
                </td>
                <td align="right">
                    <?php echo $checkup->waist_circumference?> cm
                </td>
                <td align="right">
                    <a class="button" href="<?php echo $this->url('exercises-checkup-edit') . '?checkup_id=' . $checkup->checkup_id ;?>">Edit</a>
                    <a class="button" href="<?php echo $this->url('exercises-checkup-delete') . '?checkup_id=' . $checkup->checkup_id?>">Delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else :?>
                <tr>
                    <td colspan="7" align="center">
                        No checkups
                    </td>
                </tr>
            <?php endif;?>
        </table>
    </div>
</div>




