<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle();?>
    <?php echo $this->headMeta(); ?>

    <?php //$this->headLink()->appendStylesheet(PROJECT_PATH.PUBLIC_PATH.'/hicmsAdmin/css/layout.css', 'screen',  true);?>
    <?php echo $this->headLink()->prependStylesheet($this->url('home') . '/css/site.css') ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>


    <?php //$this->headScript();?>
    <?php //$this->headScript()->appendFile('localGlobalData.js', 'text/javascript');?>
    <?php echo $this->headScript(); ?>

</head>
<body>
    <div id="body">
        <div id="nav-container">
            <ul id="nav">
                <li id="" class="level-0 nav-1 level-top first parent">
                    <a class="" href="<?php echo $this->url('exercises-home');?>">
                        <span>Exercises</span>
                    </a>
                    <ul class="">
                        <li id="" class="">
                            <a class="" href="<?php echo $this->url('exercises-checkup-home');?>">
                                <span>Checkups</span>
                            </a>
                        </li>
                        <li id="" class="">
                            <a class="" href="<?php echo $this->url('exercises-workout-home');?>">
                                <span>Workouts</span>
                            </a>
                        </li>
                        <li id="" class="">
                            <a class="" href="<?php //echo $this->url('exercises-home');?>">
                                <span>Workout Types</span>
                            </a>
                        </li>
                        <li id="" class="">
                            <a class="" href="<?php //echo $this->url('exercises-home');?>">
                                <span>Workout Groups</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li id="" class="level-0 nav-2 level-top last parent">
                    <a class="" href="">
                        <span>Nutrients</span>
                    </a>
                    <ul class="">
                        <li id="" class="">
                            <a class="" href="">
                                <span>Checkups</span>
                            </a>
                        </li>
                        <li id="" class="">
                            <a class="" href="">
                                <span>Workouts</span>
                            </a>
                        </li>
                        <li id="" class="">
                            <a class="" href="">
                                <span>Workout Types</span>
                            </a>
                        </li>
                        <li id="" class="">
                            <a class="" href="">
                                <span>Workout Groups</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        <?php echo $this->raw('content'); ?>
    </div>
    <?php
    $this->inlineScript()->appendScript(
        '
         $(document).ready(function() {
           $("ul#nav li.level-top").mouseenter(function(){
                $(this).find("ul").addClass("active");
            });

            $("ul#nav li.level-top").mouseleave(function(){
                $(this).find("ul").removeClass("active");
            });
         });

        /*function abta() {

        }*/


        '
    );

    ?>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
