<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle();?>
    <?php echo $this->headMeta(); ?>

    <?php //$this->headLink()->appendStylesheet(PROJECT_PATH.PUBLIC_PATH.'/hicmsAdmin/css/layout.css', 'screen',  true);?>
    <?php //echo $this->headLink()->prependStylesheet($this->url('home') . '/css/site.css') ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>


    <?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js', 'text/javascript');?>
    <?php //$this->headScript()->appendFile('localGlobalData.js', 'text/javascript');?>
    <?php echo $this->headScript(); ?>

</head>
<body>
    <div id="body">
        <?php echo $this->raw('content'); ?>
    </div>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
