<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php //echo $this->headLink()->prependStylesheet('/css/site.css') ?>

</head>
<body>
<?php echo $this->raw('content');
//if (!is_object($this->raw('content'))):
//    echo $this->raw('content');
//else:
//    echo "<pre>" . '"$this->raw(\'content\')" ';
//    print_r($this->raw('content'));
//    echo "</pre>";
//endif;
; ?>
</body>
</html>
