<tr class="listFilter">
    <th class=""
        <?php if (isset($this->colspan)):?>
        colspan="<?php echo $this->colspan ?>"
        <?php endif;?>
        align="center">
        <table class="filterTitle" width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td align="center" >
                    <?php echo $this->translate('filters');?>
                </td>
            </tr>
        </table>
        <table class="filterContent" width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td>
                    <?php echo $this->content;?>
                </td>
            </tr>
        </table>
    </th>
</tr>