<div id="<?php echo $this->subFormId;?>" class="rowSubForm">
    <a name="<?php echo $this->subFormId;?>" ></a>
    <table class="rowTitle" cellspacing="0" cellpadding="2" border="0" width="100%">
        <tr class="">
            <th
                class=""
                align="center"
                <?php if (isset($this->colspan)):?>
                    colspan="<?php echo $this->colspan ?>"
                <?php endif;?>
                >
                <?php echo $this->subFormName ?>
            </th>
        </tr>
<!--        <tr class="">-->
<!--            <td-->
<!--                class=""-->
<!--                align="center"-->
<!--                height="4px"-->
<!--                <?php if (isset($this->colspan)):?>-->
<!--                    colspan="<?php echo $this->colspan ?>"-->
<!--                <?php endif;?>-->
<!--                >-->
<!--            </td>-->
<!--        </tr>-->
    </table>
    <table class="rowContent" cellspacing="0" cellpadding="2" border="0" width="100%">
        <?php echo $this->content;?>
    </table>
</div>