<section id="breadcrumb" >
    <ul class="breadcrumb">
        <li>
            <a href="<?php echo $this->url('home');?>">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="<?php echo $this->url('hi-checkup');?>">HiCheckup</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="<?php echo $this->url('hi-checkup/checkup');?>">Checkup</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="<?php echo $this->url('hi-checkup/checkup/list');?>">Checkup list</a> <span class="divider">/</span>
        </li>
        <li class="active">Edit checkup</li>
    </ul>
</section>
<section id="grid" >
    <?php echo $editContainer;?>
</section>
