<div class="content-header">
    <table cellspacing="0" style="width: 100%;">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>

    <?php echo $this->grid; ?>
    <?php //echo $this->getChildHtml('grid'); ?>
</div>
