<div class="container">

    <div class="page-header grid-container-widget">
        <div class="btn-toolbar pull-right">
            <div class="btn-group">
                <?php echo $this->getButtonsHtml() ?>
            </div>
        </div>
        <h3 class="<?php echo $this->getHeaderCssClass() ?> <?php //echo $this->getHeaderWidth() ?>" style="<?php echo $this->getHeaderWidth() ?>">
            <?php echo $this->getHeaderText() ?>
        </h3>
    </div>
    <?php echo $this->getChildHtml('grid'); ?>
</div>

