<div id="breadcrumb">
    &raquo;<a href="<?php echo $this->url('home');?>">Core/index/index</a>
    &raquo;<a class="" href="<?php echo $this->url('exercises-home');?>">Exercises/index/index</a>
    &raquo;<a class="" href="<?php echo $this->url('exercises-workout-home');?>">Exercises/workout/index</a>
    &raquo;<a class="" href="<?php echo $this->url('exercises-workout-exercise-home') . '?workout_id=' . $workout->workout_id;?>">Exercises/workout/exercise/index</a>
    &raquo;>Exercises/workout/exercise/edit
</div>
<div id="menu">
    <div class="modules">
        <a class="selected" href="<?php echo $this->url('exercises-home');?>" >Exercises</a>
    </div>
    <div class="module-elements">
        <a class="selected" href="<?php echo $this->url('exercises-checkup-home');?>" >Checkups</a>
        <a href="<?php echo $this->url('exercises-workout-home');?>" >Workouts</a>
        <a href="<?php //echo $this->url('exercises-workout-type');?>" >Workout Types</a>
        <a href="<?php //echo $this->url('exercises-workout-group');?>" >Workout Groups</a>
    </div>
</div>
<div id="content">
    <?php
    $title = 'Delete workout exercise';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escape($title); ?></h1>
    <p>Are you sure that you want to delete
    '<?php echo $this->escape($exercise->exercise_id); ?>' workout exercise?
    </p>
    <?php
    $url = $this->url('exercises-workout-exercise-delete') . '?exercise_id=' . $exercise->exercise_id; ?>
    <form action="<?php echo $url; ?>" method="post">
    <div>
    <input type="hidden" name="exercise_id" value="<?php echo (int)$exercise->exercise_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
    </div>
    </form>
</div>