<?php
    $title = 'Edit workout ' . $workout->date . ' ' . date('l', strtotime($workout->date)) . ' ( id: ' . $workout->workout_id . ' ) ' . ' exercise';
    $this->headTitle($title);
?>
<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Core</a>
    &raquo; <a class="" href="<?php echo $this->url('exercises-home');?>">Exercises</a>
    &raquo; <a class="" href="<?php echo $this->url('exercises-workout-home');?>">Workouts</a>
    &raquo; <a class="selected" href="<?php echo $this->url('exercises-workout-exercise-home/wildcard', array('workou_id' => $workout->workout_id));?>"><?php echo $this->escape($title); ?></a>

</div>
<div id="content">
    <div class="page-title">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php echo $form;?>
</div>