<div class="container">
    <div class="module">
        HiCMS
    </div>
    <a href="<?php echo $this->baseUrl;?>/hicms/navigation/list" target="mainFrame">
        /hicms/navigation/list
    </a>
    <br />
    <a href="<?php echo $this->baseUrl;?>/hicms/translations/list" target="mainFrame">
        /hicms/translations/list
    </a>
    <br />
    <a href="<?php echo $this->baseUrl;?>/hicms/translationsCache/dump" target="mainFrame">
        /hicms/translationsCache/dump
    </a>
    <br />
    <a href="<?php echo $this->baseUrl;?>/hicms/translationsCache/view" target="mainFrame">
        /hicms/translationsCache/view
    </a>
    <br />
    <a href="<?php echo $this->baseUrl;?>/hicms/langs/list" target="mainFrame">
       /hicms/langs/list
    </a>
    <br />
    <a href="<?php echo $this->baseUrl;?>/hicms/langsCache/dump" target="mainFrame">
       /hicms/langsCache/dump
    </a>
</div>