<?php echo $this->doctype();?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Hi Content Manager') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <script type="text/javascript">
//            var BLANK_URL = 'http://merchline.dev/js/blank.html';
//            var BLANK_IMG = 'http://merchline.dev/js/spacer.gif';

            var BASE_URL = '<?php echo $this->basePath();?>';
            var CURRENT_URL = '<?php echo $this->url();?>';

//            var SKIN_URL = 'http://merchline.dev/skin/adminhtml/default/merchline/';
//            var FORM_KEY = 'qYgzzTJEgl3wzeh8';
        </script>

        <!-- Le styles -->
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>

        <!-- Scripts -->
        <?php echo $this->headScript() ?>
    </head>

    <body >
       <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <a class="brand" href="<?php echo $this->url('home') ?>">Hi Content Manager</a>

                    <!-- HiUser -->
                    <?php /*?>
                    <div class="btn-group pull-right <?php if (strpos($controller, 'HiUser') !== false) :?>active<?php endif;?>">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" data-target="#" href="<?php //echo $this->url('hi-user') ?>">
                            <i class="icon-user"></i> HiUser
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php //echo $this->url('hi-checkup/checkup') ?>">Account</a></li>
                            <li><a href="<?php //echo $this->url('hi-checkup/checkup/stats') ?>">Edit avatar</a></li>
                            <li><a href="<?php //echo $this->url('hi-checkup/checkup/list') ?>">Statistics</a></li>
                            <li class="divider"></li>
<!--                                    <li class="nav-header">Actions</li>-->
                            <li><a href="<?php //echo $this->url('hi-checkup/checkup-profile') ?>">Log out</a></li>
                        </ul>
                    </div><!-- /HiUser - collapse -->
                    <?php */ ?>

                    <div class="nav-collapse">
                        <ul class="nav">






                            <!-- Home -->
                            <li class="pull-left <?php if (strpos($controller, 'Application') !== false) :?>active<?php endif;?>">
                                <a href="<?php echo $this->url('home') ?>">Home</a>
                            </li><!-- /Home - collapse -->


                            <!-- HiCheckup -->
                            <li class="dropdown pull-left <?php if (strpos($controller, 'HiCheckup') !== false) :?>active<?php endif;?>" id="menu1">
                                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<?php echo $this->url('hi-checkup') ?>">
                                    HiCheckup
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup') ?>">Checkup info</a></li>
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup/stats') ?>">Checkup stats</a></li>
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup/list') ?>">Checkup list</a></li>
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup/add') ?>">Add new checkup </a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Statistics profiles</li>
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup-profile') ?>">Profiles info</a></li>
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup-profile/list') ?>">Profiles list</a></li>
                                    <li><a href="<?php echo $this->url('hi-checkup/checkup-profile/add') ?>">Add new profile</a></li>
                                </ul>
                            </li><!-- /HiCheckup - collapse -->


                            <?php /*?>
                            <!-- HiTraining -->
                            <li class="dropdown pull-left <?php if (strpos($controller, 'HiTraining') !== false) :?>active<?php endif;?>" id="menu1">
                                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<?php //echo $this->url('hi-training') ?>">
                                    HiTraining
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php //echo $this->url('hi-training/workout') ?>">Workout</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/workout/list') ?>">List</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/workout/add') ?>">Add new</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Statistics profiles</li>
                                    <li><a href="<?php //echo $this->url('hi-training/workout') ?>">Profiles info</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/workout/list') ?>">Profiles list</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/workout/add') ?>">Add new profile</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Exercise type</li>
                                    <li><a href="<?php ///echo $this->url('hi-training/exercise-type') ?>">Exercise type</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/exercise-type/stats') ?>">Stats</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/exercise-type/tree') ?>">Tree</a></li>
                                    <li><a href="<?php //echo $this->url('hi-training/exercise-type/edit-tree') ?>">Edit tree</a></li>
                                </ul>
                            </li><!-- /HiTraining - collapse -->
                            <?php */ ?>

                            <li class="divider-vertical pull-right "></li>

                        </ul>
                    </div><!-- /.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <?php echo $this->content; ?>

            <hr>

            <footer>
            <p>&copy; 2012 by Piotr Socha. All rights reserved.</p>
            </footer>

        </div><!-- /.container -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
