<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript',
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Hi Content Manager') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>



  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">Hi Content Manager</a>
          <div class="nav-collapse">
            <ul class="nav">

              <li class="<?php if (strpos($controller, 'Application') !== false) :?>active<?php endif;?>">
                <a href="<?php echo $this->url('home') ?>">Home</a>
              </li>

              <li class="<?php if (strpos($controller, 'HiTraining') !== false) :?>active<?php endif;?>">
                <a href="<?php echo $this->url('hi-training') ?>">Training</a>
                <ul class="">

                  <li class="">
                    <a href="<?php echo $this->url('hi-training/checkup') ?>">Checkup stats</a>
                  </li>

                  <li class="">
                    <a href="<?php echo $this->url('hi-training/checkup/list') ?>">Checkup list</a>
                  </li>

                  <li class="">
                    <a href="<?php echo $this->url('hi-training/checkup/list') ?>">Workout stats</a>
                  </li>

                  <li class="">
                    <a href="<?php echo $this->url('hi-training/checkup/list') ?>">Workout list</a>
                  </li>

                  <li class="">
                    <a href="<?php echo $this->url('hi-training/checkup/list') ?>">Workout exercises list</a>
                  </li>
                </ul>
              </li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <?php
    $this->inlineScript()->appendScript(
        '
         $(document).ready(function() {
           $("ul.nav li").mouseenter(function(){
                $(this).find("ul").addClass("active");
            });

            $("ul.nav li").mouseleave(function(){
                $(this).find("ul").removeClass("active");
            });
         });
        '
    );
    ?>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2012 by Piotr Socha. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

	<?php echo $this->inlineScript() ?>
  </body>
</html>
