function goBack() {
    window.location = "<?php echo $back;?>";
}

/**
 *
 */
function switchToFormType(formType) {

    //
    var elements = $('input[form_' + '0' + '="1"]');

    //
    $.each(elements, function(index, value) {
        $(value).parent().parent().css('display', 'none');
    });

    if (formType > 0) {
        var elements = $('input[form_' + formType + '="1"]');

        var odd = 1;

        //
        $.each(elements, function(index, value) {
            if (odd == 1) {
                odd = 0;
            } else {
                odd = 1;
            }

            var tr = $(value).parent().parent();

            if (odd) {
                tr.addClass('even');
            } else {
                tr.removeClass('even');
            }

            tr.css('display', 'table-row');
        });
    }
}

/**
 *
 */
function exerciseType(select) {

    var selected = select.selectedIndex;
    var typeId = select.options[selected].value;

    $.ajax({
        url: '<?php echo $ajaxFormType;?>' + typeId,
        dataType: 'json',
        success: function(data) {

            //
            switchToFormType(data.type);
        }
    });
}

/**
 *
 */
function copy() {
    //alert(document.getElementById('WorkoutExerciseRow-row-type_id').selectedIndex);

    var select = document.getElementById('WorkoutExerciseRow-row-type_id');
    var selected = select.selectedIndex;
    var typeId = select.options[selected].value;

    $.ajax({
        url: '<?php echo $ajaxLastOfType;?>' + typeId,
        success: function(data) {
            //$('.result').html(data);
            //alert('Load was performed.');
            //alert(data.exercise.exercise_id);

            $.each(data.exercise, function(index, value) {
                if (index == 'exercise_id' || index == 'workout_id' || index == 'type_id') {
                    return true; // equivalent to 'continue' with a normal for loop
                }


                $('#WorkoutExerciseRow-row-' + index).attr('value', value);

            });
        }
    });

    return false;
}

/**
 *
 */
$(document).ready(function() {
    //
    var currFormType = '<?php echo $currentFormType;?>';
    //
    switchToFormType(currFormType);
});
