<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">HiTraining</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-training/workout-exercise');?>">Workout exercise</a>
</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'Workout exercise';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    Bla Bla
</div>

