function addRow() {
    window.location = "<?php echo $add; ?>";
}

function deleteRow(id) {
	if (confirm("<?php echo 'areYouSureToDeleteThisElement';?>")) {
		window.location = "<?php echo $delete; ?>" + id;
		return true;
	} else {
		return false;
	}
}

function editRow(id) {
    window.location = "<?php echo $edit; ?>" + id ;
}
/*


function massDelete() {
    window.location = "<?php echo $exercises; ?>" + id ;
}*/