<div id="breadcrumb">
    &raquo; <a href="<?php echo $this->url('home');?>">Home</a>
    &raquo; <a href="<?php echo $this->url('hi-training');?>">Training</a>
    &raquo; <a class="selected" href="<?php echo $this->url('hi-training/checkup');?>">Checkup statisctics</a>
</div>
<div id="content">
    <div class="page-title">
        <?php
            $title = 'Checkup statistics';
            $this->headTitle($title);
        ?>
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php
    //@TODO change from array to object
    $checkupsArray = $checkups->toArray();
    ?>
    <br />
<?php $this->headScript()->appendFile('https://www.google.com/jsapi', 'text/javascript');?>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawCharts);
  function drawCharts() {
	  $( "#tabs" ).tabs();
	/**
	*
	*/
    var dataWeight = new google.visualization.DataTable();
    dataWeight.addColumn('string', 'Date');
    dataWeight.addColumn('number', 'Weight [kg]');
    dataWeight.addColumn({type:'number', role:'interval'});  // interval role col.
    dataWeight.addColumn({type:'number', role:'interval'});  // interval role col.

    dataWeight.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['weight'];?>, <?php echo $checkup['weight'] - 0.1 ;?>, <?php echo $checkup['weight'] + 0.1;?>],
      <?php endforeach;?>
    ]);

    var options = {
      //title: 'Weight'
    };

    var chartWeight = new google.visualization.LineChart(document.getElementById('weight_div'));
    chartWeight.draw(dataWeight, options);


    /**
	*
	*/
    var dataFatW = new google.visualization.DataTable();
    dataFatW.addColumn('string', 'Date');
    dataFatW.addColumn('number', 'Fat Weight [kg]');
    dataFatW.addColumn({type:'number', role:'interval'});  // interval role col.
    dataFatW.addColumn({type:'number', role:'interval'});  // interval role col.
    dataFatW.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['fat_weight'];?>, <?php echo $checkup['fat_weight_range_bottom'];?>, <?php echo $checkup['fat_weight_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Fat Weight'
//    };

    var chartFatW = new google.visualization.LineChart(document.getElementById('FatW_div'));
    chartFatW.draw(dataFatW, options);

    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Fat Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['fat_percentage'];?>, <?php echo $checkup['fat_percentage'] - 0.1 ;?>, <?php echo $checkup['fat_percentage'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartFatPercent = new google.visualization.LineChart(document.getElementById('FatPercent_div'));
    chartFatPercent.draw(data, options);

    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Muscle Weight [kg]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.

    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['muscle_weight'];?>, <?php echo $checkup['muscle_weight_range_bottom'];?>, <?php echo $checkup['muscle_weight_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Weight'
//    };

    var chartMuscleW = new google.visualization.LineChart(document.getElementById('MuscleW_div'));
    chartMuscleW.draw(data, options);

    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Muscle Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['muscle_percentage'];?>, <?php echo $checkup['muscle_percentage'] - 0.1 ;?>, <?php echo $checkup['muscle_percentage'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartMusclePercent = new google.visualization.LineChart(document.getElementById('MusclePercent_div'));
    chartMusclePercent.draw(data, options);







    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Water Weight [kg]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['water_weight'];?>, <?php echo $checkup['water_weight_range_bottom'];?>, <?php echo $checkup['water_weight_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Weight'
//    };

    var chartWaterW = new google.visualization.LineChart(document.getElementById('WaterW_div'));
    chartWaterW.draw(data, options);

    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Water Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['water_percentage'];?>, <?php echo $checkup['water_percentage'] - 0.1 ;?>, <?php echo $checkup['water_percentage'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartWaterPercent = new google.visualization.LineChart(document.getElementById('WaterPercent_div'));
    chartWaterPercent.draw(data, options);



    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Bones Weight [kg]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['bones_weight'];?>, <?php echo $checkup['bones_weight'] - 0.1 ;?>, <?php echo $checkup['bones_weight'] + 0.1;?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Weight'
//    };

    var chartBonesW = new google.visualization.LineChart(document.getElementById('BonesW_div'));
    chartBonesW.draw(data, options);

    /**
	*
	*/
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Date');
    data.addColumn('number', 'Bones Percent [%]');
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addColumn({type:'number', role:'interval'});  // interval role col.
    data.addRows([
      <?php foreach ($checkupsArray as $checkup):?>
      ['<?php echo $checkup['date'];?>', <?php echo $checkup['bones_percentage'];?>, <?php echo $checkup['bones_percentage_range_bottom'];?>, <?php echo $checkup['bones_percentage_range_top'];?>],
      <?php endforeach;?>
    ]);

//    var options = {
//      title: 'Percent'
//    };

    var chartBonesPercent = new google.visualization.LineChart(document.getElementById('BonesPercent_div'));
    chartBonesPercent.draw(data, options);


  }
</script>
	<?php
//    $this->inlineScript()->appendScript(
//        '
//         $(document).ready(function() {
//             $( "#tabs" ).tabs();
//
//         });
//        '
//    );
    ?>
	<?php
    $this->headStyle()->appendStyle(
        '
         .ui-tabs .ui-tabs-hide {
    position: absolute;
    left: -10000px;
    display: block !important;
}
        '
    );
    ?>

    <div id="tabs">
    	<ul>
    		<li><a href="#tabs-1">Weight</a></li>
    		<li><a href="#tabs-2">Fat</a></li>
    		<li><a href="#tabs-3">Muscle</a></li>
    		<li><a href="#tabs-4">Water</a></li>
    		<li><a href="#tabs-5">Bones</a></li>
    		<li><a href="#tabs-6">Calories</a></li>
    		<li><a href="#tabs-7">Circumferences</a></li>
    	</ul>
        <div id="tabs-1" style="width: 900px;">
            <div id="weight_div" style="width: 700px; height: 200px;"></div>
        </div>
        <div id="tabs-2" >
            <div id="FatW_div" style="width: 700px; height: 200px;"></div>
            <div id="FatPercent_div" style="width: 700px; height: 200px;"></div>
        </div>
        <div id="tabs-3" style="width: 900px;">
            <div id="MuscleW_div" style="width: 700px; height: 200px;"></div>
            <div id="MusclePercent_div" style="width: 700px; height: 200px;"></div>
        </div>
        <div id="tabs-4" style="width: 900px;">
            <div id="WaterW_div" style="width: 700px; height: 200px;"></div>
            <div id="WaterPercent_div" style="width: 700px; height: 200px;"></div>
        </div>
        <div id="tabs-5" style="width: 900px;">
            <div id="BonesW_div" style="width: 700px; height: 200px;"></div>
            <div id="BonesPercent_div" style="width: 700px; height: 200px;"></div>
        </div>
        <div id="tabs-6" style="width: 900px;">
<!--            <div id="BonesW_div" style="width: 700px; height: 200px;"></div>-->
<!--            <div id="BonesPercent_div" style="width: 700px; height: 200px;"></div>-->
        </div>
        <div id="tabs-7" style="width: 900px;">
<!--            <div id="BonesW_div" style="width: 700px; height: 200px;"></div>-->
<!--            <div id="BonesPercent_div" style="width: 700px; height: 200px;"></div>-->
        </div>
    </div>
</div>

