<table class="treeTitle" width="100%" cellspacing="0" cellpadding="2" border="0">
    <tr class="">
        <th class="" align="center" colspan="2">
             <?php echo $this->treeData['title'];?>
        </th>
    </tr>
    <tr class="">
        <td class="" height="4" align="center" colspan="2">
        </td>
    </tr>
</table>
<div class="tree">
    <div class="treeContent">
        <?php
            $treeError = null;
            $startLevel = 0;
            $elementCounter = 1;
            $elementCount = count($this->treeData['elements']);
        ?>
        <?php $curentLevel = $startLevel;?>
        <?php if ($this->treeData['elements']) foreach ($this->treeData['elements'] as $element):?>

            <?php if ($elementCounter== 1):?>
                <ul>
            <?php endif; //Zend_Debug::dump($element);?>

            <?php if (isset($element['level'])):?>

                <?php if ($element['level'] == $curentLevel) :?>
                     <?php if ($elementCounter > 1):?>
                        </li>
                    <?php endif; //Zend_Debug::dump($element);?>

                <?php elseif ($element['level'] > $curentLevel):?>

                    <?php $levelDiffrence = $element['level'] - $curentLevel;?>
                    <?php if ($levelDiffrence > 1):?>
                        <?php $treeError = $this->translate('Element has wrong level attribute.')?>
                        <?php break;?>
                    <?php endif;?>
                    <ul>

                <?php elseif ($element['level'] < $curentLevel):?>

                    <?php $levelDiffrence = $curentLevel - $element['level'];?>
                    <?php for($i = 0;$i < $levelDiffrence;$i++):?>
                        </li></ul>
                    <?php endfor;?>
                    </li>

                <?php endif;?>

                <li id="phtml_<?php echo $element['id'];?>" <?php if ($element['id'] == $this->treeData['selectedElement']):?><?php endif;?>><!--class="open"-->

                <?php $curentLevel = $element['level'];?>
            <?php else:?>
                <?php $treeError = $this->translate('Element doesnt have a level attribute.')?>
                <?php break;?>
            <?php endif;?>

                <a href="<?php
                echo (isset($element['link'])
                    ? $element['link']
                    : $this->treeData['globalLink'])
                    .
                    (isset($element['id'])
                    ? $element['id']
                    : $this->treeData['globalLink'])

                ;?>"><ins>&nbsp;</ins><?php echo $element['title'];?> <?php if ($this->treeData['visiblePosition']):?>(<?php echo $element['position'];?>)<?php endif;?></a>

            <?php if ($elementCounter >= $elementCount):?>
                <?php $levelDiffrence = $curentLevel - $startLevel;?>
                <?php for($i = 0;$i < $levelDiffrence + 1;$i++):?>
                    </li></ul>
                <?php endfor;?>
            <?php endif?>
            <?php $elementCounter ++;?>
        <?php endforeach;?>

        <?php if ($treeError):?>
            <?php echo $treeError;?>
        <?php endif;?>

    </div>

    <div style="clear:both;">
        &nbsp;
    </div>
</div>