<tr class="<?php if ($this->even):?>even<?php endif;?>">
  <th class="" width="25%">
      <?php echo $this->formLabel($this->element->id, $this->element->getLabel()) ?>
  </th>
  <td class="" colspan="<?php //= isset($this->options['colspan'])?$this->options['colspan']:'' ?>">
      <?php echo $this->content;?>
      <?php echo $this->element->getMessages()?$this->formErrors($this->element->getMessages()):'';?>
  </td>
</tr>