<tr class="listInfo">
    <th class=""
        <?php if (isset($this->colspan)):?>
        colspan="<?php echo $this->colspan ?>"
        <?php endif;?>
        align="center">
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td width="15%" class="elementsCount" align="left">
                    <?php echo $this->translate('elements');?>:
                        <?php if ($this->perPage && $this->elementsAllCount && $this->elementsCount):?>
                            <?php echo $this->elementsFrom;?> - <?php echo $this->elementsTo;?>
                            <?php echo $this->translate('from');?>
                            <?php echo $this->elementsAllCount;?>
                            (<?php echo $this->elementsCount;?>)
                        <?php else:?>
                            <?php echo $this->elementsCount;?>
                        <?php endif;?>
                </td>
                <td align="center">

                </td>
                <td width="15%" class="perPage" align="right">
                    <?php if ($this->availablePerPage):?>
                        <?php echo $this->translate('perPage');?>
                        <?php echo $this->formSelect(
                            $this->subFormId . '[perPage]',
                            $this->perPage,
                            array(
                                'onchange'  =>  'perPage("' . $this->subFormId . '");'
                            ),
                            $this->availablePerPage
                        );?>
                    <?php else:?>
                        <?php if ($this->perPage):?>
                            <?php echo $this->perPage;?>
                        <?php endif;?>
                    <?php endif;?>
                </td>
            </tr>
        </table>
    </th>
</tr>