<?php echo $this->__('Page') ?>
<?php
$_curPage  = $this->getCurPage();
$_lastPage = $this->getLastPageNumber();
?>

<?php if($_curPage > 1): ?>
<a href="#" title="<?php echo $this->__('First page') ?>" onclick="<?php echo $this->getGrid()->getJsObjectName() ?>.setPage('1');return false;"><i class="icon-fast-backward" title="Go to First page"></i></a>
<?php else: ?>
<i class="icon-fast-backward" title="Go to First page"></i>
<?php endif; ?>

<?php if($_curPage > 1): ?>
<a href="#" title="<?php echo $this->__('Previous page') ?>" onclick="<?php echo $this->getGrid()->getJsObjectName() ?>.setPage('<?php echo ($_curPage - 1) ?>');return false;"><i class="icon-step-backward" title="Go to Previous page"></i></a>
<?php else: ?>
<i class="icon-step-backward" title="Go to Previous page"></i>
<?php endif; ?>

<input type="text" id="<?php echo $this->getGrid()->getVarNamePage() ?>" name="<?php echo $this->getGrid()->getVarNamePage() ?>" value="<?php echo $_curPage ?>" class="page" onkeypress="<?php echo $this->getGrid()->getJsObjectName() ?>.inputPage(this, event, '<?php echo $_lastPage ?>');"/>

<?php if($_curPage < $_lastPage): ?>
    <a href="#" title="<?php echo $this->__('Next page') ?>" onclick="<?php echo $this->getGrid()->getJsObjectName() ?>.setPage('<?php echo ($_curPage+1) ?>');return false;"><i class="icon-step-forward" title="Go to Next page"></i></a>
<?php else: ?>
    <i class="icon-step-forward" title="Go to Next page"></i>
<?php endif; ?>

<?php if($_curPage < $_lastPage): ?>
<a href="#" title="<?php echo $this->__('Last page') ?>" onclick="<?php echo $this->getGrid()->getJsObjectName() ?>.setPage('<?php echo $_lastPage ?>');return false;"><i class="icon-fast-forward" title="Go to Last page"></i></a>
<?php else: ?>
<i class="icon-fast-forward" title="Go to Last page"></i>
<?php endif; ?>



<?php echo $this->__('of %s pages', $this->getLastPageNumber()) ?>
 <span class="separator">|</span>
<?php echo $this->__('View') ?>
<select class="page-size" name="<?php echo $this->getGrid()->getVarNameLimit() ?>" onchange="<?php echo $this->getGrid()->getJsObjectName() ?>.setLimit(this)">
    <option value="20"<?php if($this->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
    <option value="30"<?php if($this->getPageSize()==30): ?> selected="selected"<?php endif; ?>>30</option>
    <option value="50"<?php if($this->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
    <option value="100"<?php if($this->getPageSize()==100): ?> selected="selected"<?php endif; ?>>100</option>
    <option value="200"<?php if($this->getPageSize()==200): ?> selected="selected"<?php endif; ?>>200</option>
</select>
<?php echo $this->__('per page') ?> <span class="separator">|</span>
<?php echo $this->__('Total %d records found', $this->getSize()) ?>
<span id="<?php echo $this->getHtmlId() ?>-total-count" class="no-display"><?php //echo $this->getSize() ?></span>
