<div id="breadcrumb">
    &raquo;<a href="<?php echo $this->url('home');?>">Core/index/index</a>
    &raquo;<a class="selected" href="<?php echo $this->url('exercises-home');?>">Exercises/index/index</a>
</div>
<div id="menu">
    <div class="modules">
        <a class="selected" href="<?php echo $this->url('exercises-home');?>" >Exercises</a>
    </div>
    <div class="module-elements">
        <a href="<?php echo $this->url('exercises-checkup-home');?>" >Checkups</a>
        <a href="<?php echo $this->url('exercises-workout-home');?>" >Workouts</a>
        <a href="<?php //echo $this->url('exercises-workout-type');?>" >Workout Types</a>
        <a href="<?php //echo $this->url('exercises-workout-group');?>" >Workout Groups</a>
    </div>
</div>
<div id="content">
    <h1>Exercises</h1>
</div>
